### ISSUE TITLE
V1.4: Testing

### ISSUE THREAD

**Issue by SeeuSim** [AY2223S2-CS2103T-T13-2/tp#244]
These testers are to add tests and add test coverage for the following packages of the App:
- [x] Commons - Seeu Sim
- [ ] UI - Seeu Sim
- [ ] Models - Zong Hao
- [ ] Storage - Alson
- [ ] Logic - Alson
